dist: trusty
language: node_js
sudo: true
node_js:
  - "0.10"
before_install:
 - npm install -g npm
 - npm install -g grunt-cli
 # Download and unpack the stack executable
 - mkdir -p ~/.local/bin
 - export PATH=$HOME/.local/bin:$PATH
 - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
 # Configure stack to use the system GHC installation
 - stack config set system-ghc --global true
 - export PATH=/opt/ghc/8.0.1/bin:$PATH
 - stack setup

script:
  - cd haskellHub
  - stack build
 
addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-8.0.1
      - libc6
      - libc6-dev
install:
  - travis_wait stack --no-terminal --skip-ghc-check setup
  - travis_wait stack --no-terminal --skip-ghc-check test --only-snapshot
